### ISSUE TITLE
OpenAPI Parser Serialization

### ISSUE THREAD

**Issue by artemportnoy** [RepreZen/KaiZen-OpenApi-Parser#158]
Hi there,

I’m trying to use the library and while the parsing part is very intuitive, I’m spinning my wheels trying to understand how to use the serialization feature. The API Overview document describes a toJson() method but I don’t see it anywhere. Any pointers would be greatly appreciated!

Thank you,
Artem Portnoy

**Comment by andylowry** [comment]
Hi @artemportnoy 

My apologies, the API Overview has definitely gotten stale and needs some work. I'll try to carve out some time soon.

The `toJson` method, along with some other "framework" methods, were removed from the generated public APIs, and are now available via an adapter class. So, e.g, instead of writing `model.toJson()` you should now write `Overlay.of(model).toJson()`.

This is described in more detail [here](https://github.com/RepreZen/JsonOverlay/pull/2).

If this solves your problem, I'd appreciate your closing this issue.

Thanks!

**Comment by artemportnoy** [comment]
Okay, thank you for the quick response!

**Comment by NathanAtKadaster** [comment]
Please update this in the doumentation! I've been looking for this for the past few hours. 😭 

Glad it still works though.
