### ISSUE TITLE
Relative path in server url leads to validation failure

### ISSUE THREAD

**Issue by aleskovets** [RepreZen/KaiZen-OpenApi-Parser#209]
Sample header:
```
openapi: "3.0.0"
info:
  version: "2"
  title: "Test API"
  description: "Test API v2"

servers:
  - url: /v2
```
According to the [spec](https://swagger.io/docs/specification/api-host-and-base-path/) "/v2" is valid server path, but validation fails with error:

>  "Invalid URL '/v2': java.net.MalformedURLException: no protocol: /v2"

I am using latest code from master.

**Comment by andylowry** [comment]
Thanks @aleskovets . There are currently a number of validations that are not implemented, and others - like this one - that are broken. They were created in a mad rush back when the latest OAS specification was v3.0.0rc0, and mostly untouched since then.

The good news is that I've recently begun work on #26, and some other changes are teed up that improve the validation approach considerably. There'll be a new release shortly. It'll be a new major version - 4.x - because of some breaking changes - including, importantly, coming into structural compliance with the current version fo the specification. I'm not able to commit to a particular time frame, but I expect it will be in the next week or so, and I probably can fix this specific bug in that release.

There will still be numerous holes to fill in validation as I work through the list I'm compiling with #26, but this should be a significant improvement.

Let me know if this requires more urgent attention that I've proposed here, and I'll see what I can do.

**Comment by aleskovets** [comment]
I will gladly wait for the next major version. I have a local (admittedly quite ugly) workaround for this issue. Thank you for your work!

**Comment by tedepstein** [comment]
@andylowry, thanks for the update. 

FWIW, I would say that "false-positives" in the validation (incorrectly flagging an error condition on a valid OpenAPI document) are more urgent than false-negatives (missing validations). Only because false-positives can stop the client application in its tracks, unless there's a way to disable validation completely, which would be a pretty big sacrifice just to work around a single rogue validation.

**Comment by aleskovets** [comment]
I would agree with @tedepstein on that. In my case parser's primary job is to detect errors in document and fail build (it is integrated in CI pipeline on Jenkins)

**Comment by andylowry** [comment]
Fixed in #216

**Comment by andylowry** [comment]
@aleskovets I've got a fix for this merged into master branch. I'll be publishing the fix as part of a new major release in the next day or two. You'll probably need to adjust your dependency to pick it up (e.g. `<version>[4.0,5.0)</version>`) once it's out.

**Comment by andylowry** [comment]
@aleskovets A new 4.0.0 revision of this project is now available in maven central, and it includes a fix to this issue.

The primary reason for the move to a new major release was a "structural" upgrade of the generated classes to reflect the current revision of the OpenAPI specification. The parser previously reflected the draft revision 3.0.0-rc0. The most significant structural change was the creation of a `Discriminator` object type for the `Schema.discriminator` property, which in the draft specification was a simple string.

All that is to say that I do not expect you or many others will find that the new major version introduces breaking changes.

**Comment by aleskovets** [comment]
@andylowry, what is the artifact group/name? I only found 3.0.1: https://search.maven.org/search?q=g:com.reprezen.kaizen

**Comment by andylowry** [comment]
@aleskovets Hmm... that search service hasn't caught up. The actual repo accessed by maven is at http://repo.maven.apache.org/maven2/. Looking at http://repo.maven.apache.org/maven2/com/reprezen/kaizen/openapi-parser/ you'll find:

![image](https://user-images.githubusercontent.com/108675/45053659-9cdadd80-b058-11e8-96e7-c8ba0efec7d1.png)

**Comment by aleskovets** [comment]
Got it. Looks like it still does not work for me: I got "URL must not be a relative URL: /v2" error on validation.

**Comment by andylowry** [comment]
@aleskovets Sorry, please try again. You should get v4.0.1 now.

The "exactly what happened" thing I mentioned above was a bone-headed error on my part that really was there, but then after addressing that, I still found myself getting false positives, but only when utilizing the library in a program executed from a shell on my workstation. The same program worked fine in eclipse, and the false positives should have shown up in tests during build, but they didn't. I never did figure out what was behind that, but after a few hours of fruitless hair-pulling I took a different approach that seems much more reliable. All having to do with registering custom URL schemes with the JVM.

**Comment by aleskovets** [comment]
Thank you @andylowry ! Issue is no longer reproducible with 4.0.1

**Comment by andylowry** [comment]
@aleskovets OK, great. I'll close this issue now
