### ISSUE TITLE
How obtain the schema corresponding to an object

### ISSUE THREAD

**Issue by JPnCo** [RepreZen/KaiZen-OpenApi-Parser#81]
1 - When the type in schema is object and the schema of this object given by a reference to a schema in /components/schemas, what is the method to obtain the referenced schema ?
2 - When type is arrayand typ e of items is object, how obtain the schema of the items ?
Thanks, 
JPnCo

**Comment by andylowry** [comment]
@JPnCo 

1. How to obtain the schema object in a given context depends on the context. In general, wherever you see a place in the specification where a `Schema Object` is allowed, there is (or should be) a way to get your hands on the corresponding instance of the `Schema` class in the parsed model. For example, suppose you have:

```
components:
  schemas:
    X:
      type: object
      properties:
        y:
          $ref: "#/components/schemas/Y"
    Y:
      type: object
      properties:
        x:
          type: string
```

Then assuming variable `model` has your parsed model, `model.getSchema("X")` would give you the parsed `Schema` instance for schema `X`, and `model.getSchema("X").getProperty("y")` would give you the same `Schema` instance as would `model.getSchema("Y")`.

In other context where schemas can appear, there are always `getSchema()` methods, e.g. in `MediaType` (used in `Response`, `RequestBody`, and `Parameter` objects). The `Parameter` object also has its own `getSchema()` method, reflecting that in simple cases a `Parameter` can specify its own schema and style, while in more complex cases parameters can be defined with content based on `MediaType` objects.

Schemas that are referenced in other schemas are another case where you'll find `getSchema()` methods, sometimes with more specific names. For example:

2. If you have a `Schema` object that represents an array schema, then that object's `getItemsSchema()` method will give you the schema of the array items.

Two things you may be looking for, but which are not currently implemented, are:
* If a schema is specified via a reference, how can I know that and get details like the reference string and whether it was successfully resolved, etc?
* If the schema I'm looking at is defined as a component schema, what is its name in that structure? And in what model file did that component structure appear (in the case of multi-file models)? This is related to but a little distinct from the first case, since the starting point is the referenced schema, not the object containing the reference.

Both of these are on the way.

Let me know if none of this answered the questions you were asking, and in that case an example might add clarity.

**Comment by JPnCo** [comment]
@andylowry 
Thanks for you response. 
unfortunately, "If a schema is specified via a reference, how can I know that and get details like the reference string and whether it was successfully resolved, etc?" is exactly what I need.
Have you any information about the time when this feature will be available ?
Sincerely yours
JPnCo

**Comment by andylowry** [comment]
@JPnCo It's near the top of my list to get this and a few other reference-related items straightened out. In fact, the issue I consider most urgent at the moment is #64. Your need is covered by #75.

So hopefully it will not be long.

I've mentioned you on #75 so you can follow progress there, which probably makes this issue redundant. Please close if you agree. Thx!
